import json

nb_path = 'ContinuousHybridTracker_HarmonicMath.ipynb'
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# ── CELL A: Per-song BPM curves ───────────────────────────────────────────────
curves_cell_source = [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "n_songs = len(results)\n",
    "ncols = 2\n",
    "nrows = (n_songs + 1) // ncols\n",
    "\n",
    "fig, axes = plt.subplots(nrows, ncols, figsize=(16, nrows * 4))\n",
    "fig.patch.set_facecolor('#0d0d0d')\n",
    "axes = axes.flatten()\n",
    "\n",
    "for idx, res in enumerate(results):\n",
    "    ax = axes[idx]\n",
    "    ax.set_facecolor('#1a1a1a')\n",
    "    ax.tick_params(colors='white')\n",
    "    ax.xaxis.label.set_color('white')\n",
    "    ax.yaxis.label.set_color('white')\n",
    "    ax.title.set_color('white')\n",
    "    for spine in ax.spines.values():\n",
    "        spine.set_edgecolor('#444')\n",
    "\n",
    "    t          = res['h_time']\n",
    "    raw_bpm    = res['h_raw_bpm']\n",
    "    judge_bpm  = res['h_pearson']\n",
    "    target     = res['target_bpm']\n",
    "    name       = res['name']\n",
    "    median_bpm = res['median_bpm']\n",
    "    err        = res['error_pct']\n",
    "\n",
    "    ax.plot(t, raw_bpm,   color='#555555', linewidth=1.0, alpha=0.7, label='Fast Scout')\n",
    "    ax.plot(t, judge_bpm, color='#00e5ff', linewidth=2.0, label='Heavy Judge')\n",
    "    ax.axhline(target, color='#ffeb3b', linestyle='--', linewidth=1.5,\n",
    "               label=f'Target: {target} BPM')\n",
    "\n",
    "    # Harmonic lines (x0.5, x2)\n",
    "    ax.axhline(target * 0.5, color='#ff8f00', linestyle=':', linewidth=0.8, alpha=0.5, label=f'x0.5: {target*0.5:.0f}')\n",
    "    ax.axhline(target * 2.0, color='#ff8f00', linestyle=':', linewidth=0.8, alpha=0.5, label=f'x2: {target*2.0:.0f}')\n",
    "\n",
    "    # Error annotation\n",
    "    err_color = '#66bb6a' if err < 5 else '#ffa726' if err < 15 else '#ef5350'\n",
    "    ax.set_title(f'{name[:40]}\\nMedian: {median_bpm:.1f} BPM | Err: {err:.1f}%',\n",
    "                 fontsize=10, fontweight='bold', color=err_color)\n",
    "    ax.set_xlabel('Time (s)')\n",
    "    ax.set_ylabel('BPM')\n",
    "    ax.set_ylim(40, 240)\n",
    "    ax.grid(True, alpha=0.15)\n",
    "    ax.legend(fontsize=7, facecolor='#222', labelcolor='white', loc='upper right')\n",
    "\n",
    "# Hide any spare axes\n",
    "for idx in range(n_songs, len(axes)):\n",
    "    axes[idx].set_visible(False)\n",
    "\n",
    "fig.suptitle('Per-Song BPM Tracking Curves', fontsize=14, fontweight='bold', color='white', y=1.01)\n",
    "plt.tight_layout(pad=2.0)\n",
    "plt.savefig('per_song_curves.png', dpi=110, facecolor='#0d0d0d', bbox_inches='tight')\n",
    "plt.show()\n",
    "print('Saved: per_song_curves.png')\n",
]

# ── CELL B: Class error over time ─────────────────────────────────────────────
class_error_cell_source = [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "def bpm_to_class(bpm):\n",
    "    return np.log2(bpm / 60.0) % 1.0\n",
    "\n",
    "def circular_distance(a, b):\n",
    "    '''Shortest distance on the circular [0, 1) space'''\n",
    "    d = np.abs(np.asarray(a) - b)\n",
    "    return np.minimum(d, 1.0 - d)\n",
    "\n",
    "n_songs = len(results)\n",
    "ncols = 2\n",
    "nrows = (n_songs + 1) // ncols\n",
    "\n",
    "fig, axes = plt.subplots(nrows, ncols, figsize=(16, nrows * 4))\n",
    "fig.patch.set_facecolor('#0d0d0d')\n",
    "axes = axes.flatten()\n",
    "\n",
    "for idx, res in enumerate(results):\n",
    "    ax = axes[idx]\n",
    "    ax.set_facecolor('#1a1a1a')\n",
    "    ax.tick_params(colors='white')\n",
    "    ax.xaxis.label.set_color('white')\n",
    "    ax.yaxis.label.set_color('white')\n",
    "    ax.title.set_color('white')\n",
    "    for spine in ax.spines.values():\n",
    "        spine.set_edgecolor('#444')\n",
    "\n",
    "    t           = np.array(res['h_time'])\n",
    "    ltm_class   = np.array(res['h_ltm_class'])\n",
    "    judge_bpm   = np.array(res['h_pearson'])\n",
    "    target      = res['target_bpm']\n",
    "    name        = res['name']\n",
    "\n",
    "    target_class = bpm_to_class(target)\n",
    "\n",
    "    # Class error of the Flywheel (long_term_class) vs target\n",
    "    ltm_err  = circular_distance(ltm_class, target_class)\n",
    "\n",
    "    # Class error of the Heavy Judge output vs target\n",
    "    judge_class     = np.array([bpm_to_class(b) for b in judge_bpm])\n",
    "    # Harmonic-aware: also check x0.5 and x2 octaves\n",
    "    judge_class_h05 = np.array([bpm_to_class(b * 0.5) for b in judge_bpm])\n",
    "    judge_class_h2  = np.array([bpm_to_class(b * 2.0) for b in judge_bpm])\n",
    "    judge_err = np.minimum(\n",
    "        circular_distance(judge_class, target_class),\n",
    "        np.minimum(\n",
    "            circular_distance(judge_class_h05, target_class),\n",
    "            circular_distance(judge_class_h2,  target_class)\n",
    "        )\n",
    "    )\n",
    "\n",
    "    ax.fill_between(t, ltm_err,  alpha=0.25, color='#42a5f5')\n",
    "    ax.plot(t, ltm_err,   color='#42a5f5', linewidth=1.5, label='Flywheel (LTM) class error')\n",
    "    ax.fill_between(t, judge_err, alpha=0.2, color='#00e5ff')\n",
    "    ax.plot(t, judge_err, color='#00e5ff', linewidth=2.0, label='Heavy Judge class error (harmonic-aware)')\n",
    "\n",
    "    ax.axhline(0.05, color='#66bb6a', linestyle=':', linewidth=1.0, label='0.05 tolerance (Local Sweep radius)')\n",
    "\n",
    "    # Median error annotation\n",
    "    med_err = float(np.median(judge_err[len(judge_err)//2:]))\n",
    "    err_color = '#66bb6a' if med_err < 0.05 else '#ffa726' if med_err < 0.15 else '#ef5350'\n",
    "\n",
    "    ax.set_title(\n",
    "        f'{name[:40]}\\nTarget class: {target_class:.3f}  |  Median err: {med_err:.4f}',\n",
    "        fontsize=10, fontweight='bold', color=err_color\n",
    "    )\n",
    "    ax.set_xlabel('Time (s)')\n",
    "    ax.set_ylabel('Circular Class Distance [0, 0.5]')\n",
    "    ax.set_ylim(-0.01, 0.52)\n",
    "    ax.grid(True, alpha=0.15)\n",
    "    ax.legend(fontsize=7, facecolor='#222', labelcolor='white', loc='upper right')\n",
    "\n",
    "for idx in range(n_songs, len(axes)):\n",
    "    axes[idx].set_visible(False)\n",
    "\n",
    "fig.suptitle('BPM Class Error Over Time (circular distance from target class)',\n",
    "             fontsize=14, fontweight='bold', color='white', y=1.01)\n",
    "plt.tight_layout(pad=2.0)\n",
    "plt.savefig('class_error_curves.png', dpi=110, facecolor='#0d0d0d', bbox_inches='tight')\n",
    "plt.show()\n",
    "print('Saved: class_error_curves.png')\n",
]

# ── Append both cells ──────────────────────────────────────────────────────────
for source in [curves_cell_source, class_error_cell_source]:
    nb['cells'].append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source
    })

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Done! Two new plot cells appended.")
