import json
import os

nb_path = 'ContinuousHybridTracker_HarmonicMath.ipynb'
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_scout_cell_source = [
    "# THE INITIAL SWEEP (FAST SCOUT) - TRUE PEARSON O(1)\n",
    "def class_based_phase_sweep(odf_buffer, class_evals, **kwargs):\n",
    "    odf_size = len(odf_buffer)\n",
    "    decay_curve = np.exp(-1.5 * np.linspace(1.0, 0.0, odf_size))\n",
    "    weighted_buffer = odf_buffer * decay_curve\n",
    "    \n",
    "    buffer_mean = np.mean(weighted_buffer)\n",
    "    buffer_centered = weighted_buffer - buffer_mean\n",
    "    buffer_std = np.sqrt(np.sum(buffer_centered**2)) + 1e-6\n",
    "    \n",
    "    best_overall_score = -float('inf')\n",
    "    best_overall_class = class_evals[0] % 1.0\n",
    "    \n",
    "    for class_val in class_evals:\n",
    "        c = class_val % 1.0\n",
    "        base_bpm = 60.0 * (2 ** c)\n",
    "        eval_bpm = base_bpm if base_bpm >= 90.0 else base_bpm * 2.0\n",
    "        \n",
    "        normalized_template = template_bank.get_template(eval_bpm)\n",
    "        p_scores = (normalized_template @ buffer_centered) / buffer_std\n",
    "        \n",
    "        # Human Prior injected into Fast Scout to fix Song 3 polyrhythms!\n",
    "        human_prior = 0.5 + 0.5 * np.exp(-0.5 * ((eval_bpm - 125.0) / 40.0)**2)\n",
    "        tau_max_score = np.max(p_scores) * human_prior\n",
    "        \n",
    "        if tau_max_score > best_overall_score:\n",
    "            best_overall_score = tau_max_score\n",
    "            best_overall_class = c\n",
    "            \n",
    "    return best_overall_class, best_overall_score\n"
]

new_run_simulation_cell = [
    "def run_simulation(y_list):\n",
    "    print(f\"\\n🚀 Starting Fast-Scout/Heavy-Judge Simulation with Bass+High Filter (ONSET DRIVEN)...\")\n",
    "    infos = default_infos()\n",
    "    infos[\"printAsservmentDetails\"] = False \n",
    "    infos[\"useMicrophone\"] = True\n",
    "\n",
    "    SIMULATED_FPS = 60.0\n",
    "    TIME_PER_FRAME = 1.0 / SIMULATED_FPS\n",
    "    CHUNK_SIZE_FOR_60FPS = int(44100 / SIMULATED_FPS)\n",
    "\n",
    "    class MockTime:\n",
    "        def __init__(self): self.current_time = 0.0\n",
    "        def time(self): return self.current_time\n",
    "\n",
    "    mock_timer = MockTime()\n",
    "    ListenerModule.time.time = mock_timer.time\n",
    "\n",
    "    listener = ListenerModule.Listener(infos)\n",
    "    listener.ingestion.momentum_multiplier = 0.01\n",
    "    listener.dynamic_audio_latency = 0\n",
    "\n",
    "    y_full = np.concatenate(y_list)\n",
    "    mic = Robust_Simulated_Microphone(y_full, listener.ingestion.fft_band_values, infos)\n",
    "    listener.hasBeenSilenceCalibrated = True\n",
    "    listener.hasBeenBBCalibrated = True\n",
    "    listener.ingestion.calibrate_silence = lambda fps_ratio: None\n",
    "    listener.ingestion.calibrate_bb = lambda fps_ratio: None\n",
    "\n",
    "    # Metrics\n",
    "    history_time = []\n",
    "    history_raw_bpm = []\n",
    "    history_pearson = []\n",
    "    history_class = []\n",
    "    history_ltm_class = []\n",
    "\n",
    "    audio_time = 0.0\n",
    "    playhead_time = 0.0\n",
    "    frame = 0\n",
    "\n",
    "    last_strong_sweep_time = -8.0\n",
    "    smoothed_flux = 0.0\n",
    "    long_term_class = 0.0\n",
    "    \n",
    "    # CUSTOM BASS + HIGH ODF BUFFER\n",
    "    custom_odf_buffer = np.zeros(300)\n",
    "    prev_bands = np.zeros(len(listener.ingestion.fft_band_values))\n",
    "\n",
    "    while mic.pop_chunk(CHUNK_SIZE_FOR_60FPS):\n",
    "        mic.calculate_fft()\n",
    "        listener.update()\n",
    "        \n",
    "        current_bands = np.array(listener.ingestion.fft_band_values)\n",
    "        flux_bands = np.maximum(0, current_bands - prev_bands)\n",
    "        prev_bands = current_bands\n",
    "        \n",
    "        custom_flux = np.sum(flux_bands[0:2]) + np.sum(flux_bands[-2:])\n",
    "        custom_odf_buffer = np.roll(custom_odf_buffer, -1)\n",
    "        custom_odf_buffer[-1] = custom_flux\n",
    "        \n",
    "        # SIMULATE BTRACK PEAK DETECTION\n",
    "        smoothed_flux = 0.95 * smoothed_flux + 0.05 * custom_flux\n",
    "        is_peak = custom_flux > (smoothed_flux * 1.8 + 0.1)\n",
    "        \n",
    "        # ONLY RUN MATH ON BEATS (TRANSIENTS)\n",
    "        if is_peak:\n",
    "            if playhead_time - last_strong_sweep_time >= 8.0:\n",
    "                # STRONG SWEEP: Full [0.0, 1.0) range every 8 seconds\n",
    "                class_evals = np.arange(0.0, 1.0, 0.01)\n",
    "                last_strong_sweep_time = playhead_time\n",
    "            else:\n",
    "                # LOCAL SWEEP: Window around long_term_class\n",
    "                class_evals = np.arange(long_term_class - 0.05, long_term_class + 0.05 + 0.001, 0.01)\n",
    "\n",
    "            best_class, raw_score = class_based_phase_sweep(\n",
    "                custom_odf_buffer, class_evals=class_evals)\n",
    "            \n",
    "            min_d, aligned_class = harmonic_alignment(best_class, long_term_class)\n",
    "            \n",
    "            if playhead_time < 5.0:\n",
    "                long_term_class = aligned_class\n",
    "            else:\n",
    "                diff = (aligned_class - long_term_class + 0.5) % 1.0 - 0.5\n",
    "                long_term_class = (long_term_class + 0.1 * diff) % 1.0\n",
    "                \n",
    "            candidates = class_to_bpm_candidates(long_term_class)\n",
    "            \n",
    "            bpm_pearson, score_pearson = evaluate_specific_bpms(custom_odf_buffer, candidates)\n",
    "\n",
    "            winning_class = bpm_to_class(bpm_pearson)\n",
    "            min_d_win, aligned_winning_class = harmonic_alignment(winning_class, long_term_class)\n",
    "            diff_win = (aligned_winning_class - long_term_class + 0.5) % 1.0 - 0.5\n",
    "            long_term_class = (long_term_class + 0.5 * diff_win) % 1.0 \n",
    "            \n",
    "            listener.analyzer.bpm = bpm_pearson\n",
    "            \n",
    "        if frame % int(SIMULATED_FPS) == 0:\n",
    "            history_time.append(playhead_time)\n",
    "            history_raw_bpm.append(60.0 * (2 ** best_class) if 'best_class' in locals() else 120)\n",
    "            history_pearson.append(bpm_pearson if 'bpm_pearson' in locals() else 120)\n",
    "            history_class.append(best_class if 'best_class' in locals() else 0)\n",
    "            history_ltm_class.append(long_term_class)\n",
    "\n",
    "        audio_time += TIME_PER_FRAME\n",
    "        mock_timer.current_time += TIME_PER_FRAME\n",
    "        playhead_time += TIME_PER_FRAME\n",
    "        frame += 1\n",
    "\n",
    "    ListenerModule.time.time = time.time \n",
    "    \n",
    "    print(\"Simulation Complete!\")\n",
    "    return history_time, history_raw_bpm, history_pearson, history_class, history_ltm_class\n"
]

for cell in nb['cells']:
    if cell['cell_type'] == 'code':
        source = "".join(cell['source'])
        if "def run_simulation(y_list):" in source:
            cell['source'] = new_run_simulation_cell
        elif "def class_based_phase_sweep" in source:
            cell['source'] = new_scout_cell_source

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
