import json

nb_path = 'ContinuousHybridTracker_HarmonicMath.ipynb'
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# ── New run_simulation with the flywheel-from-judge fix ──────────────────────
new_run_simulation_cell = [
    "import time as _time_module\n",
    "def run_simulation(y_list):\n",
    "    print('Starting Onset-Driven Simulation with FakeListener...')\n",
    "\n",
    "    SIMULATED_FPS = 60.0\n",
    "    TIME_PER_FRAME = 1.0 / SIMULATED_FPS\n",
    "    CHUNK_SIZE = int(44100 / SIMULATED_FPS)\n",
    "\n",
    "    listener = FakeListener()\n",
    "    y_full   = np.concatenate(y_list)\n",
    "\n",
    "    # ---- Simulated Microphone (Mel-filter) ----\n",
    "    NB_BANDS    = FakeListener.NB_BANDS\n",
    "    BUFFER_SIZE = 1024\n",
    "    SR          = 44100\n",
    "    audio_buffer = np.zeros(BUFFER_SIZE)\n",
    "    fft_size     = BUFFER_SIZE // 2 + 1\n",
    "\n",
    "    def hz_to_mel(f): return 2595 * np.log10(1 + f / 700.0)\n",
    "    def mel_to_hz(m): return 700 * (10**(m / 2595.0) - 1)\n",
    "    lower_mel = hz_to_mel(20);  upper_mel = hz_to_mel(20000)\n",
    "    mel_pts   = np.linspace(lower_mel, upper_mel, NB_BANDS + 2)\n",
    "    hz_pts    = mel_to_hz(mel_pts)\n",
    "    bin_pts   = np.floor((BUFFER_SIZE + 1) * hz_pts / SR).astype(int)\n",
    "    W = np.zeros((NB_BANDS, fft_size))\n",
    "    for i in range(NB_BANDS):\n",
    "        s, m, e = (min(bin_pts[i+k], fft_size-1) for k in range(3))\n",
    "        if m > s: W[i, s:m] = np.linspace(0, 1, m-s, endpoint=False)\n",
    "        if e > m: W[i, m:e] = np.linspace(1, 0, e-m, endpoint=False)\n",
    "        tot = W[i].sum()\n",
    "        if tot > 0: W[i] /= tot\n",
    "    hanning = np.hanning(BUFFER_SIZE)\n",
    "\n",
    "    # ---- Tracking state ----\n",
    "    history_time, history_raw_bpm, history_pearson, history_class, history_ltm_class = [], [], [], [], []\n",
    "    playhead_time = 0.0\n",
    "    frame = 0\n",
    "    pos = 0\n",
    "\n",
    "    last_strong_sweep_time = -8.0\n",
    "    smoothed_flux  = 0.0\n",
    "    long_term_class = 0.0\n",
    "    custom_odf_buffer = np.zeros(300)\n",
    "    prev_bands = np.zeros(NB_BANDS)\n",
    "\n",
    "    best_class  = 0.0\n",
    "    bpm_pearson = 120.0\n",
    "\n",
    "    # Profiling\n",
    "    profile = {'ingestion': 0.0, 'listener_update': 0.0, 'flux': 0.0,\n",
    "               'scout': 0.0, 'alignment': 0.0, 'judge': 0.0}\n",
    "    pc = _time_module.perf_counter\n",
    "\n",
    "    while pos + CHUNK_SIZE <= len(y_full):\n",
    "        # --- Mic ingestion ---\n",
    "        t0 = pc()\n",
    "        chunk = y_full[pos: pos + CHUNK_SIZE]; pos += CHUNK_SIZE\n",
    "        audio_buffer = np.roll(audio_buffer, -CHUNK_SIZE)\n",
    "        audio_buffer[-CHUNK_SIZE:] = chunk\n",
    "        fft_result = np.abs(np.fft.rfft(audio_buffer * hanning))\n",
    "        mel = np.dot(W, fft_result) * (150.0 / (BUFFER_SIZE / 1024.0))\n",
    "        listener.fft_band_values[:] = mel.astype(int)\n",
    "        profile['ingestion'] += pc() - t0\n",
    "\n",
    "        # --- FakeListener update ---\n",
    "        t0 = pc()\n",
    "        listener.update(fps_ratio=1.0)\n",
    "        profile['listener_update'] += pc() - t0\n",
    "\n",
    "        # --- Flux + onset detection ---\n",
    "        t0 = pc()\n",
    "        current_bands = np.array(listener.fft_band_values)\n",
    "        flux_bands    = np.maximum(0, current_bands - prev_bands)\n",
    "        prev_bands    = current_bands\n",
    "        custom_flux   = np.sum(flux_bands[0:2]) + np.sum(flux_bands[-2:])\n",
    "        custom_odf_buffer = np.roll(custom_odf_buffer, -1)\n",
    "        custom_odf_buffer[-1] = custom_flux\n",
    "        smoothed_flux = 0.95 * smoothed_flux + 0.05 * custom_flux\n",
    "        is_peak = custom_flux > (smoothed_flux * 1.8 + 0.1)\n",
    "        profile['flux'] += pc() - t0\n",
    "\n",
    "        if is_peak:\n",
    "            if playhead_time - last_strong_sweep_time >= 8.0:\n",
    "                class_evals = np.arange(0.0, 1.0, 0.01)\n",
    "                last_strong_sweep_time = playhead_time\n",
    "            else:\n",
    "                class_evals = np.arange(long_term_class - 0.05, long_term_class + 0.05 + 0.001, 0.01)\n",
    "\n",
    "            # 1. FAST SCOUT\n",
    "            t0 = pc()\n",
    "            best_class, _ = class_based_phase_sweep(custom_odf_buffer, class_evals)\n",
    "            profile['scout'] += pc() - t0\n",
    "\n",
    "            # 2. FLYWHEEL UPDATE FROM SCOUT (weak, harmonic-aware)\n",
    "            t0 = pc()\n",
    "            min_d, aligned_class = harmonic_alignment(best_class, long_term_class)\n",
    "            if playhead_time < 5.0:\n",
    "                long_term_class = aligned_class\n",
    "            else:\n",
    "                diff = (aligned_class - long_term_class + 0.5) % 1.0 - 0.5\n",
    "                long_term_class = (long_term_class + 0.1 * diff) % 1.0\n",
    "            candidates = class_to_bpm_candidates(long_term_class)\n",
    "            profile['alignment'] += pc() - t0\n",
    "\n",
    "            # 3. HEAVY JUDGE\n",
    "            t0 = pc()\n",
    "            bpm_pearson, score_pearson = evaluate_specific_bpms(custom_odf_buffer, candidates)\n",
    "            profile['judge'] += pc() - t0\n",
    "\n",
    "            # 4. FLYWHEEL UPDATE FROM JUDGE (strong, DIRECT - no harmonic alignment)\n",
    "            # The Judge already evaluated multiple harmonics and picked the best one.\n",
    "            # Applying harmonic_alignment here maps the correct class BACK to the\n",
    "            # wrong flywheel class via fifth-aliasing (the Stayin' Alive bug).\n",
    "            # Instead, pull directly toward the Judge's class with a strong step.\n",
    "            winning_class = bpm_to_class(bpm_pearson)\n",
    "            diff_win = (winning_class - long_term_class + 0.5) % 1.0 - 0.5\n",
    "            long_term_class = (long_term_class + 0.5 * diff_win) % 1.0\n",
    "\n",
    "            listener.bpm = bpm_pearson\n",
    "\n",
    "        if frame % int(SIMULATED_FPS) == 0:\n",
    "            history_time.append(playhead_time)\n",
    "            history_raw_bpm.append(60.0 * (2 ** best_class))\n",
    "            history_pearson.append(bpm_pearson)\n",
    "            history_class.append(best_class)\n",
    "            history_ltm_class.append(long_term_class)\n",
    "\n",
    "        playhead_time += TIME_PER_FRAME\n",
    "        frame += 1\n",
    "\n",
    "    print('Simulation Complete!')\n",
    "    print('\\n=== PROFILING RESULTS ===')\n",
    "    for k, v in profile.items():\n",
    "        print(f'  {k:25s}: {v:.3f} s')\n",
    "    return history_time, history_raw_bpm, history_pearson, history_class, history_ltm_class\n",
]

# Patch
patched = False
for cell in nb['cells']:
    if cell['cell_type'] == 'code' and "def run_simulation(y_list):" in "".join(cell['source']):
        cell['source'] = new_run_simulation_cell
        patched = True
        break

print(f"run_simulation patched: {patched}")

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Done!")
