import json

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# \ud83d\udd2c Sub-BPM Resolution Pure Template Benchmark\n",
        "This notebook generates the structured bipolar pulse template for every 0.5 BPM interval from 60 to 180 BPM, utilizing continuous-phase float arrays. It uses the pre-loaded Librosa array to fix MP3 codec truncation issues.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import librosa\n",
        "import numpy as np\n",
        "import time\n",
        "from collections import deque\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "# Import core infrastructure\n",
        "import core.Listener as ListenerModule\n",
        "from IPython.display import display, clear_output\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "def default_infos():\n",
        "    return {\n",
        "        \"startServer\"     : False ,\n",
        "        \"useGlobalMatrix\" : False ,\n",
        "        \"useMicrophone\"   : True  ,\n",
        "        \"HARDWARE_MODE\"   : \"simulation\",\n",
        "        \"printTimeOfCalculation\" : False ,\n",
        "        \"printModesDetails\"      : True ,\n",
        "        \"printMicrophoneDetails\" : False ,\n",
        "        \"printAppDetails\"        : False ,\n",
        "        \"printAsservmentDetails\" : False ,\n",
        "        \"printConfigurationLoads\": False ,\n",
        "        \"printConfigChanges\"     : False ,\n",
        "        \"modesToPrintDetails\"    : [\"PSG\"]\n",
        "    }\n",
        "\n",
        "AUDIO_FILE = 'mp3_files/Nightcall.mp3'\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 1. Ground Truth Benchmark\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(f\"Loading {AUDIO_FILE} full audio for Ground Truth Benchmarks...\")\n",
        "y_full, sr = librosa.load(AUDIO_FILE, sr=44100) # Force 44.1kHz to match our standard\n",
        "\n",
        "print(\"Running non-causal Librosa Beat Track...\")\n",
        "onset_env_full = librosa.onset.onset_strength(y=y_full, sr=sr)\n",
        "tempo_librosa, beat_frames_true = librosa.beat.beat_track(onset_envelope=onset_env_full, sr=sr)\n",
        "true_beat_times = librosa.frames_to_time(beat_frames_true, sr=sr)\n",
        "print(f\"\u2705 Ground Truth Extraction Complete! Librosa Global BPM: {tempo_librosa[0] if isinstance(tempo_librosa, np.ndarray) else tempo_librosa:.1f}\")\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 2. High Resolution Continuous-Phase Template Evaluation\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "class Robust_Simulated_Microphone:\n",
        "    def __init__(self, y_full_array, bandValues, infos):\n",
        "        self.bandValues = bandValues\n",
        "        self.nb_of_fft_band = len(self.bandValues)\n",
        "        \n",
        "        self.sample_rate = 44100\n",
        "        self.buffer_size = 1024 \n",
        "        self.audio_data = np.zeros(self.buffer_size)\n",
        "        \n",
        "        # Use Librosa's array directly to avoid Torchaudio MP3 truncation\n",
        "        self.full_audio = y_full_array\n",
        "        self.total_samples = len(self.full_audio)\n",
        "        self.current_pos = 0\n",
        "        \n",
        "        fft_size = self.buffer_size // 2 + 1\n",
        "        self.weight_matrix = np.zeros((self.nb_of_fft_band, fft_size))\n",
        "        \n",
        "        def hz_to_mel(f): return 2595 * np.log10(1 + f / 700.0)\n",
        "        def mel_to_hz(m): return 700 * (10**(m / 2595.0) - 1)\n",
        "        \n",
        "        lower_mel = hz_to_mel(20)\n",
        "        upper_mel = hz_to_mel(20000)\n",
        "        mel_points = np.linspace(lower_mel, upper_mel, self.nb_of_fft_band + 2)\n",
        "        hz_points = mel_to_hz(mel_points)\n",
        "        bin_points = np.floor((self.buffer_size + 1) * hz_points / self.sample_rate).astype(int)\n",
        "        \n",
        "        for i in range(self.nb_of_fft_band):\n",
        "            start = min(bin_points[i], fft_size - 1)\n",
        "            mid = min(bin_points[i + 1], fft_size - 1)\n",
        "            end = min(bin_points[i + 2], fft_size - 1)\n",
        "            if mid > start:\n",
        "                self.weight_matrix[i, start:mid] = np.linspace(0, 1, mid - start, endpoint=False)\n",
        "            if end > mid:\n",
        "                self.weight_matrix[i, mid:end] = np.linspace(1, 0, end - mid, endpoint=False)\n",
        "            band_sum = np.sum(self.weight_matrix[i, :])\n",
        "            if band_sum > 0:\n",
        "                self.weight_matrix[i, :] /= band_sum\n",
        "                \n",
        "        self.raw_fft_history = None\n",
        "        self.high_res_flux = 0.0\n",
        "\n",
        "    def pop_chunk(self, chunk_size=1024):\n",
        "        if self.current_pos + chunk_size > self.total_samples:\n",
        "            return False \n",
        "        \n",
        "        incoming = self.full_audio[self.current_pos : self.current_pos + chunk_size]\n",
        "        self.current_pos += chunk_size\n",
        "        self.audio_data = np.roll(self.audio_data, -chunk_size)\n",
        "        self.audio_data[-chunk_size:] = incoming\n",
        "        return True\n",
        "\n",
        "    def calculate_fft(self):\n",
        "        windowed_data = self.audio_data * np.hanning(self.buffer_size)\n",
        "        fft_result = np.abs(np.fft.rfft(windowed_data))\n",
        "        \n",
        "        scale = 150.0 / (self.buffer_size / 1024.0)\n",
        "        mel_bands = np.dot(self.weight_matrix, fft_result) * scale\n",
        "        for i in range(self.nb_of_fft_band):\n",
        "            self.bandValues[i] = int(mel_bands[i])\n",
        "\n",
        "        if self.raw_fft_history is not None:\n",
        "            freq_diff = np.maximum(0, fft_result[5:300] - self.raw_fft_history[5:300])\n",
        "            self.high_res_flux = np.sum(freq_diff)\n",
        "        self.raw_fft_history = fft_result\n",
        "        \n",
        "        \n",
        "def continuous_phase_sweep(odf_buffer):\n",
        "    odf_size = len(odf_buffer)\n",
        "    decay_curve = np.exp(-1.5 * np.linspace(1.0, 0.0, odf_size))\n",
        "    weighted_buffer = odf_buffer * decay_curve\n",
        "    \n",
        "    best_overall_score = -float('inf')\n",
        "    best_overall_bpm = 60.0\n",
        "    \n",
        "    buffer_indices = np.arange(odf_size)\n",
        "    \n",
        "    # Explicit 0.5 BPM sub-resolution array\n",
        "    bpm_evals = np.arange(60.0, 180.5, 0.5)\n",
        "    all_scores = []\n",
        "    \n",
        "    btrack_fps = 60.0\n",
        "    \n",
        "    for bpm_val in bpm_evals:\n",
        "        # Calculate tau as a continuous float value\n",
        "        tau_val = 60.0 * btrack_fps / bpm_val\n",
        "        \n",
        "        # We sweep integral phase offsets from 0 to ceil(tau_val)\n",
        "        p_max = int(np.ceil(tau_val))\n",
        "        p_scores = np.zeros(p_max)\n",
        "        \n",
        "        for p in range(p_max):\n",
        "            # Calculate floating point phase for each buffer index\n",
        "            phase_float = (buffer_indices - (odf_size - 1 - p)) % tau_val\n",
        "            norm_phi = phase_float / tau_val # Normalized phase 0.0 -> 1.0\n",
        "            \n",
        "            # Construct bipolar vector array map\n",
        "            template_vals = np.full(odf_size, -0.2)\n",
        "            template_vals[(norm_phi <= 0.05) | (norm_phi >= 0.95)] = 1.0\n",
        "            template_vals[(norm_phi >= 0.45) & (norm_phi <= 0.55)] = 0.6\n",
        "            template_vals[(norm_phi >= 0.22) & (norm_phi <= 0.28)] = 0.3\n",
        "            template_vals[(norm_phi >= 0.72) & (norm_phi <= 0.78)] = 0.3\n",
        "            \n",
        "            p_scores[p] = np.sum(weighted_buffer * template_vals)\n",
        "            \n",
        "        tau_max_score = np.max(p_scores)\n",
        "        \n",
        "        # Gaussian smoothing to prioritize plausible 120bpm range\n",
        "        gaussian_weight = np.exp(-0.5 * ((bpm_val - 120.0) / 20.0)**2)\n",
        "        weighted_score = tau_max_score * (0.8 + 0.2 * gaussian_weight)\n",
        "        \n",
        "        all_scores.append(weighted_score)\n",
        "        \n",
        "        if weighted_score > best_overall_score:\n",
        "            best_overall_score = weighted_score\n",
        "            best_overall_bpm = bpm_val\n",
        "            \n",
        "    return best_overall_bpm, all_scores, bpm_evals\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 3. Execution Engine\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "infos = default_infos()\n",
        "infos[\"printAsservmentDetails\"] = False \n",
        "infos[\"useMicrophone\"] = True\n",
        "\n",
        "SIMULATED_FPS = 60.0\n",
        "TIME_PER_FRAME = 1.0 / SIMULATED_FPS\n",
        "CHUNK_SIZE_FOR_60FPS = int(44100 / SIMULATED_FPS)\n",
        "\n",
        "class MockTime:\n",
        "    def __init__(self):\n",
        "        self.current_time = 0.0\n",
        "    def time(self):\n",
        "        return self.current_time\n",
        "\n",
        "mock_timer = MockTime()\n",
        "ListenerModule.time.time = mock_timer.time\n",
        "\n",
        "listener = ListenerModule.Listener(infos)\n",
        "mic = Robust_Simulated_Microphone(y_full, listener.fft_band_values, infos)\n",
        "listener.hasBeenSilenceCalibrated = True\n",
        "listener.hasBeenBBCalibrated = True\n",
        "listener.calibrate_silence = lambda: None\n",
        "listener.calibrate_bb = lambda: None\n",
        "\n",
        "history_time = []\n",
        "history_bpm = []\n",
        "history_all_scores = []\n",
        "audio_time = 0.0\n",
        "\n",
        "frames_since_sweep = 0\n",
        "frames_between_sweep = int(0.2 * SIMULATED_FPS) \n",
        "\n",
        "print(\"\ud83d\ude80 Starting High-Res Brute-Force Sweep Simulation...\")\n",
        "\n",
        "while mic.pop_chunk(CHUNK_SIZE_FOR_60FPS):\n",
        "    mic.calculate_fft()\n",
        "    listener.update() \n",
        "    \n",
        "    if frames_since_sweep >= frames_between_sweep:\n",
        "        best_bpm, all_scores, bpm_eval_range = continuous_phase_sweep(listener.odf_buffer)\n",
        "        \n",
        "        history_time.append(audio_time)\n",
        "        history_bpm.append(best_bpm)\n",
        "        history_all_scores.append(all_scores)\n",
        "        frames_since_sweep = 0\n",
        "        \n",
        "        if len(history_bpm) % 25 == 0:\n",
        "            print(f\"Time: {audio_time:.2f}s | Optimal Match: {best_bpm:.1f} BPM\")\n",
        "            \n",
        "    frames_since_sweep += 1\n",
        "    audio_time += TIME_PER_FRAME\n",
        "    mock_timer.current_time = audio_time\n",
        "\n",
        "print(\"Simulated complete!\")\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 4. Plot Evaluation\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import matplotlib.pyplot as plt\n",
        "\n",
        "plt.figure(figsize=(20, 8))\n",
        "\n",
        "# Convert scores to 2D numpy array [Time, BPM] -> [BPM, Time]\n",
        "score_matrix = np.array(history_all_scores).T\n",
        "\n",
        "time_grid = np.array(history_time)\n",
        "bpm_grid = np.array(bpm_eval_range)\n",
        "\n",
        "plt.pcolormesh(time_grid, bpm_grid, score_matrix, shading='auto', cmap='inferno')\n",
        "plt.colorbar(label='Correlation Score')\n",
        "\n",
        "plt.plot(history_time, history_bpm, label='Template Max-Score BPM', color='cyan', linewidth=2)\n",
        "\n",
        "true_tempo = float(tempo_librosa[0] if isinstance(tempo_librosa, np.ndarray) else tempo_librosa)\n",
        "plt.axhline(y=true_tempo, color='lime', linestyle='--', alpha=0.8, label=f'Librosa True BPM ({true_tempo:.1f})')\n",
        "\n",
        "plt.title('Rhythm Heatmap: Correlation Scores vs Time (0.5 BPM Resolution)')\n",
        "plt.xlabel('Time (seconds)')\n",
        "plt.ylabel('Evaluated BPM')\n",
        "plt.xlim(5.0, min(100.0, time_grid[-1] if len(time_grid) > 0 else 25.0)) # Show up to the first 100 seconds\n",
        "plt.ylim(min(bpm_grid), max(bpm_grid))\n",
        "plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n"
      ]
    }
  ],
  "metadata": {},
  "nbformat": 4,
  "nbformat_minor": 5
}

with open('TemplateSweepTracker.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2)
print('Generated TemplateSweepTracker.ipynb!')
