import json

with open("MusicAnalyzer.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

# CELL 1
cell_1 = [
    "# Ensure you have librosa installed! \n",
    "import sys\n",
    "import os\n",
    "import time\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import librosa\n",
    "import torch\n",
    "import builtins\n",
    "import torchaudio\n",
    "\n",
    "# Add the root 'vialactee' folder to path so we can import 'core'\n",
    "sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..'))) \n",
    "from core.Listener import Listener\n",
    "\n",
    "# --- CONFIGURATION ---\n",
    "AUDIO_FILE = \"C:/Users/Users/Desktop/vialactée/vialactee/mp3_files/Palladium.mp3\" # CHANGE THIS PATH TO YOUR MP3!\n",
    "TOLERANCE_WINDOW = 0.150  # Seconds. An algorithmic beat within 150ms of a true beat counts as a Hit.\n",
    "\n",
    "print(f\"Loading '{AUDIO_FILE}' globally for Ground Truth extraction...\")\n",
    "# Load audio using librosa for the gold standard offline beat tracking\n",
    "y, sr = librosa.load(AUDIO_FILE, sr=None) \n",
    "print(\"Extracting actual temporal ground truth...\")\n",
    "tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)\n",
    "RAW_true_beats = librosa.frames_to_time(beat_frames, sr=sr)\n",
    "\n",
    "print(\"Generating continuous Ground Truth phase timeline...\")\n",
    "bpm = tempo[0]\n",
    "beat_phase = 0.0\n",
    "continuous_true_beats = []\n",
    "continuous_true_subbeats = []\n",
    "\n",
    "raw_idx = 0\n",
    "current_time = 0.0\n",
    "dt = 1.0 / 60.0\n",
    "total_time = len(y) / sr\n",
    "\n",
    "while current_time <= total_time:\n",
    "    phase_increment = (bpm / 60.0) * dt\n",
    "    last_phase = beat_phase\n",
    "    beat_phase += phase_increment\n",
    "    \n",
    "    # Soft sync to raw librosa beats to catch any drift or tempo changes\n",
    "    if raw_idx < len(RAW_true_beats):\n",
    "        dist = RAW_true_beats[raw_idx] - current_time\n",
    "        if dist < -0.15:\n",
    "            raw_idx += 1\n",
    "        elif abs(dist) < 0.150:\n",
    "            ideal_phase = (1.0 - (dist * bpm / 60.0)) % 1.0\n",
    "            phase_diff = (ideal_phase - beat_phase + 0.5) % 1.0 - 0.5\n",
    "            beat_phase += phase_diff * 0.05\n",
    "            \n",
    "    if last_phase < 0.5 and beat_phase >= 0.5:\n",
    "        continuous_true_subbeats.append(current_time)\n",
    "        \n",
    "    if beat_phase >= 1.0:\n",
    "        beat_phase -= 1.0\n",
    "        continuous_true_beats.append(current_time)\n",
    "        \n",
    "    current_time += dt\n",
    "\n",
    "true_beat_times = np.array(continuous_true_beats)\n",
    "true_subbeat_times = np.array(continuous_true_subbeats)\n",
    "\n",
    "print(f\"Ground Truth established! Freewheeled {len(true_beat_times)} true beats and {len(true_subbeat_times)} true sub-beats at {bpm:.1f} BPM.\")\n"
]

nb["cells"][1]["source"] = cell_1

# CELL 3
cell_3 = [
    "infos = {\"printAsservmentDetails\": False, \"useMicrophone\": True ,\n",
    "        \"momentum_mult\": 15,\n",
    "        \"base_pull\":0.005}\n",
    "\n",
    "\n",
    "SIMULATED_FPS = 60.0\n",
    "TIME_PER_FRAME = 1.0 / SIMULATED_FPS\n",
    "\n",
    "class MockTime:\n",
    "    def __init__(self):\n",
    "        self.current_time = 0.0\n",
    "    def time(self):\n",
    "        return self.current_time\n",
    "\n",
    "mock_timer = MockTime()\n",
    "import core.Listener as ListenerModule\n",
    "ListenerModule.time.time = mock_timer.time\n",
    "\n",
    "# Initialize Listener AFTER mocking time, so last_beat_time is perfectly synced to 0.0!\n",
    "listener = ListenerModule.Listener(infos)\n",
    "\n",
    "mic = Simulated_Microphone(AUDIO_FILE, listener.fft_band_values, infos)\n",
    "listener.hasBeenSilenceCalibrated = True\n",
    "listener.hasBeenBBCalibrated = True\n",
    "listener.calibrate_silence = lambda: None\n",
    "listener.calibrate_bb = lambda: None\n",
    "\n",
    "# Data collectors\n",
    "history_time = []\n",
    "history_bpm = []\n",
    "history_binary_trust = []\n",
    "history_bpm_trust = []\n",
    "history_bass_flux = []\n",
    "algorithmic_beats = []\n",
    "algorithmic_sub_beats = []\n",
    "\n",
    "print(\"🚀 Starting Fast-Forward Live Analysis...\")\n",
    "start_real_world_time = time.time()\n",
    "CHUNK_SIZE_FOR_60FPS = int(44100 / 60.0)\n",
    "\n",
    "last_logged_beat_count = 0\n",
    "last_logged_beat_phase = 0.0\n",
    "frame = 0\n",
    "\n",
    "while mic.pop_chunk(CHUNK_SIZE_FOR_60FPS):\n",
    "    mic.calculate_fft()\n",
    "    listener.update()\n",
    "    \n",
    "    # We define an algorithmic 'beat' to occur whenever the beat_count increments.\n",
    "    if getattr(listener, 'beat_count', 0) > last_logged_beat_count:\n",
    "        algorithmic_beats.append(mock_timer.current_time)\n",
    "        last_logged_beat_count = listener.beat_count\n",
    "        \n",
    "    # We define an algorithmic 'sub-beat' when beat_phase crosses 0.5\n",
    "    current_phase = getattr(listener, 'beat_phase', 0.0)\n",
    "    if last_logged_beat_phase < 0.5 and current_phase >= 0.5:\n",
    "        algorithmic_sub_beats.append(mock_timer.current_time)\n",
    "    last_logged_beat_phase = current_phase\n",
    "    \n",
    "    history_time.append(mock_timer.current_time)\n",
    "    history_bpm.append(listener.bpm)\n",
    "    history_binary_trust.append(getattr(listener, 'binary_trust', 0.0))\n",
    "    history_bpm_trust.append(getattr(listener, 'bpm_trust', 0.0))\n",
    "    history_bass_flux.append(listener.band_flux[0] + listener.band_flux[1])\n",
    "    \n",
    "    # Step simulated time\n",
    "    mock_timer.current_time += TIME_PER_FRAME\n",
    "    frame += 1\n",
    "    \n",
    "    if frame % 1800 == 0:\n",
    "        print(f\"Proccessed {mock_timer.current_time:.1f}s...\")\n",
    "\n",
    "ListenerModule.time.time = time.time # Restore time\n",
    "\n",
    "alg_beats_array = np.array(algorithmic_beats)\n",
    "alg_sub_beats_array = np.array(algorithmic_sub_beats)\n",
    "print(f\"✅ Finished! Extracted {len(alg_beats_array)} algorithmic beats and {len(alg_sub_beats_array)} algorithmic sub-beats.\")\n"
]

nb["cells"][3]["source"] = cell_3

# CELL 4
cell_4 = [
    "# EVALUATING ALGORITHMIC PERFORMANCE VS GROUND TRUTH\n",
    "def evaluate_single_stream(alg_stream, true_stream, tolerance=0.150):\n",
    "    matched_true = set()\n",
    "    matched_alg = set()\n",
    "    \n",
    "    for i, a_beat in enumerate(alg_stream):\n",
    "        closest_dist = float('inf')\n",
    "        closest_j = -1\n",
    "        for j, t_beat in enumerate(true_stream):\n",
    "            if j in matched_true: continue\n",
    "            dist = abs(a_beat - t_beat)\n",
    "            if dist < closest_dist and dist <= tolerance:\n",
    "                closest_dist = dist\n",
    "                closest_j = j\n",
    "                \n",
    "        if closest_j != -1:\n",
    "            matched_true.add(closest_j)\n",
    "            matched_alg.add(i)\n",
    "            \n",
    "    hits = len(matched_alg)\n",
    "    false_positives = len(alg_stream) - hits\n",
    "    false_negatives = len(true_stream) - hits\n",
    "    \n",
    "    precision = hits / len(alg_stream) if len(alg_stream) > 0 else 0\n",
    "    recall = hits / len(true_stream) if len(true_stream) > 0 else 0\n",
    "    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0\n",
    "    return hits, false_positives, false_negatives, precision, recall, f1_score, matched_alg, matched_true\n",
    "\n",
    "m_hits, m_wrongs, m_misses, m_precision, m_recall, m_f1, m_alg_main, m_true = evaluate_single_stream(alg_beats_array, true_beat_times, TOLERANCE_WINDOW)\n",
    "s_hits, s_wrongs, s_misses, s_precision, s_recall, s_f1, m_alg_sub, m_true_sub = evaluate_single_stream(alg_sub_beats_array, true_subbeat_times, TOLERANCE_WINDOW)\n",
    "\n",
    "total_hits = m_hits + s_hits\n",
    "total_wrongs = m_wrongs + s_wrongs\n",
    "total_misses = m_misses + s_misses\n",
    "total_alg = len(alg_beats_array) + len(alg_sub_beats_array)\n",
    "total_true = len(true_beat_times) + len(true_subbeat_times)\n",
    "\n",
    "tot_precision = total_hits / total_alg if total_alg > 0 else 0\n",
    "tot_recall = total_hits / total_true if total_true > 0 else 0\n",
    "tot_f1 = 2 * (tot_precision * tot_recall) / (tot_precision + tot_recall) if (tot_precision + tot_recall) > 0 else 0\n",
    "\n",
    "print(\"============ 📈 EVALUATION REPORT ============\")\n",
    "print(f\"Tolerance Window: +/- {int(TOLERANCE_WINDOW*1000)}ms\")\n",
    "print(f\"Total True Beats: {len(true_beat_times)} | Total Sub-beats: {len(true_subbeat_times)}\")\n",
    "print(f\"Total Algorithmic Beats: {len(alg_beats_array)} | Total Algorithmic Sub-beats: {len(alg_sub_beats_array)}\")\n",
    "print(\"----------------------------------------------\")\n",
    "print(f\"\\u2705 RIGHT (Main Beats): {m_hits} perfectly synced.\")\n",
    "print(f\"\\u2611\\ufe0f RIGHT (Sub-Beats): {s_hits} perfectly synced.\")\n",
    "print(f\"\\u274c WRONG (False Positives): {total_wrongs} extra/ghost commands.\")\n",
    "print(f\"\\U0001f47b MISSED (True commands): {total_misses} true beats slipped through.\")\n",
    "print(\"----------------------------------------------\")\n",
    "print(f\"\\U0001f3af Precision: {tot_precision*100:.1f}%\")\n",
    "print(f\"\\U0001f3c5 Recall: {tot_recall*100:.1f}%\")\n",
    "print(f\"\\U0001f3c6 F1-SCORE (Overall Sync Quality): {tot_f1*100:.1f}%\")\n",
    "print(\"==============================================\")\n"
]

nb["cells"][4]["source"] = cell_4


# For CELL 5, we need to carefully replace just the lines referencing matched sets to draw them properly!
# But since I don't know EXACTLY what cell 5 looks like without errors, I'll extract it, print it to a file, and change it!
# Wait, I CAN just modify the loops that draw.
# Let's write the whole Cell 5 too!
cell_5 = [
    "# Ploting Everything!\n",
    "time_arr = np.array(history_time)\n",
    "bpm_arr = np.array(history_bpm)\n",
    "b_trust_arr = np.array(history_binary_trust)\n",
    "bpm_trust_arr = np.array(history_bpm_trust)\n",
    "bass_flux_arr = np.array(history_bass_flux)\n",
    "\n",
    "fig, axs = plt.subplots(4, 1, figsize=(15, 14), sharex=True)\n",
    "\n",
    "time_slice = (5.0, 20.0)\n",
    "slice_mask = (time_arr >= time_slice[0]) & (time_arr <= time_slice[1])\n",
    "slice_times = time_arr[slice_mask]\n",
    "\n",
    "# 1. Plot Bass Flux & Ground Truth Beats\n",
    "axs[0].plot(slice_times, bass_flux_arr[slice_mask], label=\"Bass Flux\", color=\"purple\", alpha=0.6)\n",
    "for tb in true_beat_times:\n",
    "    if time_slice[0] <= tb <= time_slice[1]:\n",
    "        axs[0].axvline(tb, color='blue', linestyle='--', alpha=0.3)\n",
    "for sb in true_subbeat_times:\n",
    "    if time_slice[0] <= sb <= time_slice[1]:\n",
    "        axs[0].axvline(sb, color='cyan', linestyle=':', alpha=0.3)\n",
    "# The first ones to hit the label requirement\n",
    "axs[0].axvline(-1, color='blue', linestyle='--', alpha=0.3, label=\"True Beat\")\n",
    "axs[0].axvline(-1, color='cyan', linestyle=':', alpha=0.3, label=\"True Sub-Beat\")\n",
    "axs[0].set_title(\"Audio Transients vs Ground Truth Rhythm\")\n",
    "axs[0].legend(loc=\"upper right\")\n",
    "\n",
    "# 2. Algorithmic Tracker Output\n",
    "axs[1].plot(slice_times, bass_flux_arr[slice_mask] * 0, alpha=0)\n",
    "\n",
    "correct_beats = [alg_beats_array[i] for i in m_alg_main]\n",
    "false_beats = [alg_beats_array[i] for i in range(len(alg_beats_array)) if i not in m_alg_main]\n",
    "correct_subbeats = [alg_sub_beats_array[i] for i in m_alg_sub]\n",
    "false_subbeats = [alg_sub_beats_array[i] for i in range(len(alg_sub_beats_array)) if i not in m_alg_sub]\n",
    "\n",
    "for b in correct_beats:\n",
    "    if time_slice[0] <= b <= time_slice[1]:\n",
    "        axs[1].axvline(b, color='green', linestyle='-', linewidth=2)\n",
    "for b in false_beats:\n",
    "    if time_slice[0] <= b <= time_slice[1]:\n",
    "        axs[1].axvline(b, color='red', linestyle='-', linewidth=2)\n",
    "for b in correct_subbeats:\n",
    "    if time_slice[0] <= b <= time_slice[1]:\n",
    "        axs[1].axvline(b, color='green', linestyle=':', linewidth=2, alpha=0.6)\n",
    "for b in false_subbeats:\n",
    "    if time_slice[0] <= b <= time_slice[1]:\n",
    "        axs[1].axvline(b, color='red', linestyle=':', linewidth=2, alpha=0.6)\n",
    "\n",
    "# Mock limits for legend\n",
    "axs[1].axvline(-1, color='green', linestyle='-', linewidth=2, label=\"Hit Beat\")\n",
    "axs[1].axvline(-1, color='red', linestyle='-', linewidth=2, label=\"False Beat\")\n",
    "axs[1].axvline(-1, color='green', linestyle=':', linewidth=2, label=\"Hit Subbeat\")\n",
    "axs[1].axvline(-1, color='red', linestyle=':', linewidth=2, label=\"False Subbeat\")\n",
    "axs[1].set_title(\"Algorithmic Command Alignment\")\n",
    "axs[1].legend(loc=\"upper right\")\n",
    "\n",
    "# 3. BPM Tracking\n",
    "axs[2].plot(slice_times, bpm_arr[slice_mask], color=\"orange\", linewidth=2)\n",
    "axs[2].set_title(\"Target Tempo (BPM)\")\n",
    "\n",
    "# 4. Trust \n",
    "axs[3].plot(slice_times, b_trust_arr[slice_mask], label=\"Binary Peak Trust\", color=\"gray\", alpha=0.5)\n",
    "axs[3].plot(slice_times, bpm_trust_arr[slice_mask], label=\"Phase Locked Trust\", color=\"black\", linewidth=2)\n",
    "axs[3].set_title(\"BPM Confidence / PLL Inertia\")\n",
    "axs[3].set_ylim(-0.1, 1.1)\n",
    "axs[3].legend(loc=\"upper right\")\n",
    "\n",
    "plt.xlim(time_slice)\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]
nb["cells"][5]["source"] = cell_5

with open("MusicAnalyzer.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2)

print("SUCCESS: Notebook updated!")
